### ISSUE TITLE
请问有处理宏的办法吗？

### ISSUE THREAD

**Issue by vkensou** [SakuraEngine/SakuraShaderLanguage#2]
写unity的shader的时候会大量依赖宏，尤其是Varings结构体会根据宏变化。
我有没想到如何处理这种情况。

**Comment by vkensou** [comment]
我目前写shader的方式是用宏控制结构，再用函数填进去。所以我想编译shader可以分为三步，而不是直接把c#翻译成hlsl。第一步是定义shader结构，第二步再把c#函数翻译成hlsl，最后填充到结构中。
比如一个前向渲染的shader的结构可以是这样的：顶点变形->表面属性计算->表面属性转换为光照参数->光照方程->颜色后处理。第一步定义结构，比如顶点变形是可选的，光照方程可以选lambert也可以选brdf，还有定义各种渲染状态blend、depth等，以及不同LOD的配置；第二步将相应的函数编译成hlsl；最后再组装。
不过我说的这个更适用vs、ps，可能cs更简单一点。

**Comment by vkensou** [comment]
> 我目前写shader的方式是用宏控制结构，再用函数填进去。所以我想编译shader可以分为三步，而不是直接把c#翻译成hlsl。第一步是定义shader结构，第二步再把c#函数翻译成hlsl，最后填充到结构中。 比如一个前向渲染的shader的结构可以是这样的：顶点变形->表面属性计算->表面属性转换为光照参数->光照方程->颜色后处理。第一步定义结构，比如顶点变形是可选的，光照方程可以选lambert也可以选brdf，还有定义各种渲染状态blend、depth等，以及不同LOD的配置；第二步将相应的函数编译成hlsl；最后再组装。 不过我说的这个更适用vs、ps，可能cs更简单一点。

这里第二步还有点麻烦，hlsl里函数的参数类型也可以是宏定义的。这就需要多态了，要能根据第一步的配置选择正确的函数重载版本。

**Comment by SaeruHikari** [comment]
目标语言不只有 HLSL，还有 GLSL、MSL 以及 PSSL2。并且本仓库的主要目的之一就是使用 const spec 替代 Macros。
核心做法是利用 RoslynAPI 对 AST 进行修饰重构以及常量重写等操作，再进一步转译到其他语言。
在这里的讨论与本仓库无关且过于麻烦，感兴趣的话可以加群：537126975

**Comment by vkensou** [comment]
> 目标语言不只有 HLSL，还有 GLSL、MSL 以及 PSSL2。并且本仓库的主要目的之一就是使用 const spec 替代 Macros。 核心做法是利用 RoslynAPI 对 AST 进行修饰重构以及常量重写等操作，再进一步转译到其他语言。 在这里的讨论与本仓库无关且过于麻烦，感兴趣的话可以加群：537126975

是qq群吗？搜不到

**Comment by SaeruHikari** [comment]
> > 目标语言不只有 HLSL，还有 GLSL、MSL 以及 PSSL2。并且本仓库的主要目的之一就是使用 const spec 替代 Macros。 核心做法是利用 RoslynAPI 对 AST 进行修饰重构以及常量重写等操作，再进一步转译到其他语言。 在这里的讨论与本仓库无关且过于麻烦，感兴趣的话可以加群：537126975
> 
> 是qq群吗？搜不到

改了下可被搜索，再看看
